version: 2.1
jobs:
  check_format:
    docker:
      - image: greenbone/build-env-gvm-libs-master-debian-buster-clang-core
    steps:
      - checkout
      - run:
          name: Check Source Format
          command: clang-format -i -style=file src/*.c && git diff --exit-code
  build_gcc_core:
    docker:
      - image: greenbone/build-env-openvas-scanner-master-debian-buster-gcc-core
    steps:
      - run:
          working_directory: ~/gvm-libs
          name: Checkout gvm-libs
          command: git clone --depth 1 https://github.com/greenbone/gvm-libs.git
      - run:
          working_directory: ~/gvm-libs
          name: Configure and compile gvm-libs
          command: pushd gvm-libs && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && make install && popd
      - checkout
      - run:
          name: Configure and Compile
          command: mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && make install
  scan_build:
    docker:
      - image: greenbone/build-env-openvas-scanner-master-debian-buster-clang-core
    steps:
      - run:
          working_directory: ~/gvm-libs
          name: Checkout gvm-libs
          command: git clone --depth 1 https://github.com/greenbone/gvm-libs.git
      - run:
          working_directory: ~/gvm-libs
          name: Configure and compile gvm-libs
          command: pushd gvm-libs && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Debug .. && make install && popd
      - checkout
      - run:
          name: Configure and Scan Build
          command: mkdir build && cd build/ && scan-build cmake -DCMAKE_BUILD_TYPE=Debug .. && scan-build -o ~/scan-build-report make
      - store_artifacts:
          path: ~/scan-build-report
  gen_xml_doc:
    docker:
      - image: greenbone/code-metrics-doxygen-debian-stretch
    steps:
      - checkout
      - run:
          name: Generate documentation (XML)
          command: mkdir build && cd build/ && cmake -DSKIP_SRC=1 .. && make doc-xml 2> ~/doxygen-stderr.txt
      - store_artifacts:
          path: ~/doxygen-stderr.txt
      - persist_to_workspace:
          root: ~/project/build/doc/generated/
          paths:
            - xml
  doc_coverage:
    docker:
      - image: circleci/python:3.6
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Install coverxygen and codecov
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install 'coverxygen>=1.3.1' codecov
      - run:
          name: Establish documentation coverage
          command: |
            . venv/bin/activate
            python -m coverxygen --src-dir /root/project --xml-dir /tmp/workspace/xml --output lcov.info
      - run:
          name: Upload coverage to Codecov
          command: |
            . venv/bin/activate
            codecov -F documentation -X gcov -f lcov.info
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - check_format
      - build_gcc_core
      - scan_build
      - gen_xml_doc
      - doc_coverage:
          requires:
            - gen_xml_doc
