name: 'Build Boreas'
description: 'builds Boreas from source'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Build Boreas
      run: |
        apt-get update && apt-get install --no-install-recommends --no-install-suggests -y \
        build-essential \
        curl \
        cmake \
        pkg-config \
        libglib2.0-dev \
        libgnutls28-dev \
        libpcap-dev \
        && rm -rf /var/lib/apt/lists/*
