name: Container

on:
  push:
    branches: [ main, stable ]
    tags: ["v*"]
  workflow_dispatch:
  repository_dispatch:

jobs:
  main:
    needs: build
    name: "Upload production image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gather container image tags
        uses: greenbone/actions/container-image-tags@v1
        id: container
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          push: true
          tags: ${{ steps.container.outputs.image-tags }}
          file: .docker/prod.Dockerfile
          build-args: |
            REPOSITORY=${{ github.repository }}

  build:
    name: "Upload images for building boreas"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find reference branch
        uses: greenbone/actions/container-image-tags@v1
        id: container
        with:
          image-name: ${{ github.repository }}-build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "Build and push ${{ steps.container.outputs.image-tags }}"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.container.outputs.image-tags }}
          file: .docker/build.Dockerfile
